### ISSUE TITLE
Wiki points to an inaccessible link

### ISSUE THREAD

**Issue by farhanalam** [GameProgressive/RetroSpySDK#17]
https://github.com/GameProgressive/RetroSpySDK/wiki

When I click the link under "Additional notes can be found here.", I get a permission message. 

Screenshot:

![image](https://user-images.githubusercontent.com/578541/47681902-c3208380-db98-11e8-8f12-c3956fbb1fdf.png)

**Comment by OmniBlade** [comment]
The additional notes page does not actually exist so the wiki tried to let you make the page, but because you don't have permissions to edit the wiki, you get the error.

**Comment by farhanalam** [comment]
Is it meant to serve as a placeholder?

**Comment by arves100** [comment]
Yeah sort of

Il mer 31 ott 2018, 20:12 Farhan Alam <notifications@github.com> ha scritto:
