### ISSUE TITLE
A lot of the converted GS_ASSERT lines are missing their closing semi-colon.

### ISSUE THREAD

**Issue by OmniBlade** [GameProgressive/RetroSpySDK#19]
Master doesn't currently compile for me due to missing ';' for several GS_ASSERT lines.

**Comment by arves100** [comment]
Commit d3da88848e8cfc709774387cd7117649aa4e41ed should fix the issue. Let me know if it still doesn't work.

**Comment by OmniBlade** [comment]
lines 801 and 802 in serverbrowsing/sb_server.c and line 350 in qr2/qr2csample/qr2csample.c still appear to have the issue in master.

**Comment by arves100** [comment]
Last commit should fix the issues 060ace35150a2d5477549ab6b588fa464ed73b40

**Comment by OmniBlade** [comment]
Seems to build fine now.
