### ISSUE TITLE
Add 'gameID' to WebServices

### ISSUE THREAD

**Issue by arves100** [GameProgressive/RetroSpySDK#3]
OpenSDK uses a newer version of WebService SDK (witch unfortunally we don't have access to source code since it was a prebuilded library), on the header file (saved in this SDK as `AuthServiceOpen.h`) there are contained several functions that make use of a new parametra called gameID (On the current SDK it's not present).

In my opition, this part was added to allow GS-SDK to connect with a specific gameID. (Witch could be used, for example, to block access to old games?)

However, this new parametra **MUST** be merged in order to compile Brigades SDK.

**Comment by OmniBlade** [comment]
Is the prebuilt library a static library and do we have access to it? Might be possible to reverse it based on the info we already have and the header so we can work out what was added and implement it in this version of the SDK.

**Comment by arves100** [comment]
I forgot about that, GameSpy Tech provided a library for Windows, Linux and PS3 (It should be a static one), I will push it in this days.

**Comment by arves100** [comment]
@OmniBlade Added in [bbdef9da6437dcec1b25dd6844a23ff332e0c2ac] if you want to take a look.

**Comment by OmniBlade** [comment]
Looks like we could be good to go with this, I should be able to go through the web services functions and update them to match the code found in the static libs.

**Comment by arves100** [comment]
Added as of eeb0ce40012cd03539d0d83f9faa7c949c4fd701.
